version: '3.7'
name: quix-template-llm-support
services:

  redpanda:
    container_name: redpanda
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.19
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      # Address the broker advertises to clients that connect to the Kafka API.
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      # Redpanda brokers use the RPC API to communicate with each other internally.
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
    ports:
      - 18081:8081
      - 18082:8082
      - 19092:9092
      - 19644:9644
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"
        ]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s

  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.3.8
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: true
          clusters:
            - name: local-connect-cluster
              url: http://connect:8083
    ports:
      - 8080:8080
    depends_on:
      - redpanda

  redis:
    container_name: redis
    image: redislabs/rejson:latest
    ports:
      - 6379:6379

  ai-customer:
    container_name: ai-customer
    build:
      context: "./AI Customer"
    env_file:
      - shared.env
    environment:
      - broker_address=redpanda:9092
      - topic=ai-chat-history
      - keep_timing=1
      - conversation_length=15
    depends_on:
      - redpanda

  ai-customer-support-agent:
    container_name: ai-customer-support-agent
    build:
      context: "./AI Customer Support Agent"
    env_file:
      - shared.env
    environment:
      - broker_address=redpanda:9092
      - topic=ai-chat-history
    depends_on:
      - redpanda

  sentiment-analyzer:
    container_name: sentiment-analyzer
    build:
      context: "./Sentiment Analyzer"
    env_file:
      - shared.env
    environment:
      - broker_address=redpanda:9092
      - input=ai-chat-history
      - output=ai-chat-history-with-sentiment
      - buffer_delay=0
    depends_on:
      - redpanda

  redis-sink:
    container_name: redis-sink
    build:
      context: "./Redis Sink"
    env_file:
      - shared.env
    environment:
      - broker_address=redpanda:9092
      - input=ai-chat-history-with-sentiment
      - expire_after=1440
      - redis_host=redis
      - redis_port=6379
      - redis_user=
      - redis_pwd=
    depends_on:
      - redpanda
      - redis

  # Note that this is not able to interact because the workspace id is
  # not interpreted correctly.
  # demo-webshop-frontend:
  #   container_name: demo-webshop-frontend
  #   build:
  #     context: "./Demo webshop frontend"
  #   env_file:
  #     - shared.env
  #   environment:
  #     - bearer_token=
  #     - offers_topic=special-offers
  #     - click_topic=click-data
  #   ports:
  #     - 8080:80

  customer-support-dashboard:
    container_name: customer-support-dashboard
    build:
      context: "./Streamlit Dashboard"
    env_file:
      - shared.env
    environment:
      - redis_host=redis
      - redis_port=6379
      - redis_pwd=
      - redis_user=
      - chat_count=12
      - style_sheet=style.css
    ports:
      - 8501:8501
    depends_on:
      - redis
