name: AI Support Agent
language: python
variables:
  - name: input
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: agent-topic
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
