name: AI Support Agent
language: python
variables:
  - name: topic
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: chat-1
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
