name: Converstations sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: drafts
    required: false
  - name: consumer_group
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
