name: PromptController
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: sentiment
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: messages
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
