name: AI Customer
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: messages
    required: true
  - name: product
    inputType: FreeText
    description: ''
    defaultValue: printer
    required: true
  - name: draft_topic
    inputType: InputTopic
    description: ''
    defaultValue: drafts
    required: true
  - name: scenario
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: true
  - name: role
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
