name: Quix External Topic Connector
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: hello-world-source
    required: true
  - name: input
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: true
  - name: external_token
    inputType: Secret
    description: ''
    defaultValue: external_token
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
