name: ConversationStarter
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: messages
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
