name: Redis Sink
language: python
variables:
  - name: redis_host
    inputType: Secret
    description: Redis host.
    defaultValue: redis_host
    required: true
  - name: redis_port
    inputType: Secret
    description: Redis port.
    defaultValue: redis_port
    required: true
  - name: redis_pwd
    inputType: Secret
    description: Redis password.
    defaultValue: redis_pwd
    required: true
  - name: expire_after
    inputType: FreeText
    description: Conversation storage duration in minutes.
    defaultValue: 1440
    required: true
  - name: mysecret
    inputType: Secret
    description: ''
    defaultValue: influxdb_token
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
